### ISSUE TITLE
ElasticSearch instrumentation raise an error from v2.0.0 and upward

### ISSUE THREAD

**Issue by nmussat** [scoutapp/scout_apm_python#150]
Performing ES search in a Django view raise an exception with Scout APM v2.0.0.
Same code with Scout v1.3.8 worked as expected.
Disabling the instrumentation with `SCOUT_DISABLED_INSTRUMENTS='elasticsearch'` circumvents the issue.

## Project dependencies

- Django==2.0.9
- django-elasticsearch-dsl==0.5.0
- elasticsearch==6.2.0
- elasticsearch-dsl==6.1.0

## Stack trace

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/usr/src/app/prose/backoffice/views/salon.py", line 56, in get_queryset
    queryset = search.to_queryset()
  File "/usr/local/lib/python3.6/site-packages/django_elasticsearch_dsl/search.py", line 28, in to_queryset
    pks = [result._id for result in s]
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 306, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 679, in execute
    **self._params
  File "/usr/local/lib/python3.6/site-packages/scout_apm/core/monkey.py", line 243, in __call__
    self.__subject__, self._eop_instance_, *args, **kwargs
  File "<string>", line 5, in search
AttributeError: 'list' object has no attribute 'title'
```

**Comment by dlanderson** [comment]
Thanks for the report - we'll investigate.

**Comment by RobertHWChiangSV** [comment]
Hi, how is this issue going ?

**Comment by nmussat** [comment]
Hi,

We're still stuck on the old Python package version.
We're not feeling super confident upgrading, now that we've seen our app
broken :/

*Nicolas Mussat*
CTO & Cofounder
PROSE
134 Spring street, 5th floor, New York NY 10012 - USA
100 boulevard de Sebastopol, 75003 Paris - France

**Comment by adamchainz** [comment]
Hi @nmussat, I'm Adam and I'm helping with maintenance of this package now.

I have a fix in #156 .  The funny thing about it, and the Git history, is that it implies that the Elasticsearch integration would never have worked for you. Did you ever see Elasticsearch in your traces on Scout?

Thanks,

Adam

**Comment by nmussat** [comment]
Hi!

Now that you mention it, I don't remember seeing anything ES related in
Scout.
We don't use ElasticSearch that much, it's just powering our internal
backoffice tool search engine and isn't mission critical, that might
explain why I didn't care about gathering more ES info.

Thanks for the followup, I really appreciate it.
Looking forward to testing this fix!

Thanks,
*Nicolas Mussat*
CTO & Cofounder
PROSE
134 Spring street, 5th floor, New York NY 10012 - USA
100 boulevard de Sebastopol, 75003 Paris - France

**Comment by adamchainz** [comment]
Thanks for the info. Will let you know when the release goes out.

**Comment by adamchainz** [comment]
Hi @nmussat 

Sorry for slowness here: the fix was released a couple weeks ago in version 2.0.3, and 2.0.4 has come out since. (See https://github.com/scoutapp/scout_apm_python/blob/master/CHANGELOG.md ).

Would you mind checking if your problem is resolved?

Thanks,

Adam

**Comment by RobertHWChiangSV** [comment]
Our problem is resolved after upgrading to `2.0.4`.

**Comment by adamchainz** [comment]
@mattgaff Hi, you reported having the same issue on Slack with version 2.0.4, Python 2.7, and Django 1.11. I've just looked for ways this could still be happening, but I can't spot anything obvious. Do you have a stack trace? Also what versions of `django-elasticsearch-dsl`, `elasticsearch-dsl`, and `elasticsearch` are you using?

**Comment by nmussat** [comment]
Hi!

I'm afraid that's not me: we're on Django 2.0, Python 3.6 and still haven't
updated our Scout package.
What email address was use on your Slack?

Thanks,
*Nicolas Mussat*
CTO & Cofounder
PROSE
134 Spring street, 5th floor, New York NY 10012 - USA
100 boulevard de Sebastopol, 75003 Paris - France

**Comment by adamchainz** [comment]
Sorry to annoy you on the same issue @nmussat , it was @mattgaff on Slack. Next time I'll open a new issue instead!
