### ISSUE TITLE
Exception `AttributeError: 'int' object has no attribute 'to_bytes'` 

### ISSUE THREAD

**Issue by bkvirendra** [scoutapp/scout_apm_python#44]
Getting exception with Django 1.11.9 when using `scout_apm` integration, unable to get it started.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/scout_apm/core/socket.py", line 80, in run
    self._register()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/scout_apm/core/socket.py", line 157, in _register
    key=self.config.value('key')))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/scout_apm/core/socket.py", line 128, in _send
    self.socket.sendall(self._message_length(data))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/scout_apm/core/socket.py", line 143, in _message_length
    return length.to_bytes(4, 'big')
AttributeError: 'int' object has no attribute 'to_bytes'
```

My environment is as follows:
Python 2.7.12
Django 1.11.9
OS Ubuntu 16.04

**Comment by cschneid** [comment]
Hi @bkvirendra we have a few known issues with python 2.7 keeping it from working. We intend to support it before coming out of tech preview, but for the moment it's broken. I'm sorry for the issue.

**Comment by cschneid** [comment]
Closing this, since #56 fixed it. Keep track of the 2.7 support ticket (#45)
