### ISSUE TITLE
CoreAgent fails to start. Alpine

### ISSUE THREAD

**Issue by Vladkryvoruchko** [scoutapp/scout_apm_python#484]
Having the same issue, described in https://github.com/scoutapp/scout-apm-php/issues/162 , while running scout-apm under alpine:

```*** Starting uWSGI 2.0.18 (64bit) on [Tue Feb 18 20:24:34 2020] ***
compiled with version: 8.3.0 on 18 February 2020 19:15:22
os: Linux-4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018
nodename: 9b511eeb30b9
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /leads
detected binary path: /leads/env/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
*** starting uWSGI Emperor ***
*** Emperor stats server enabled on 0.0.0.0:9191 fd: 4 ***
*** has_emperor mode detected (fd: 7) ***
[uWSGI] getting INI configuration from leads.ini
Tue Feb 18 20:24:34 2020 - [emperor] vassal leads.ini has been spawned
*** Starting uWSGI 2.0.18 (64bit) on [Tue Feb 18 20:24:34 2020] ***
compiled with version: 8.3.0 on 18 February 2020 19:15:22
os: Linux-4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018
nodename: 9b511eeb30b9
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /leads
detected binary path: /leads/env/bin/uwsgi
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 0.0.0.0:80 fd 8
uwsgi socket 0 bound to TCP address 127.0.0.1:33271 (port auto-assigned) fd 6
Python version: 3.6.9 (default, Oct 17 2019, 11:10:22)  [GCC 8.3.0]
Python main interpreter initialized at 0x561d95a59fe0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 375600 bytes (366 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 8, cores: 6)
spawned uWSGI worker 2 (pid: 9, cores: 6)
spawned uWSGI http 1 (pid: 11)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x561d95a59fe0 pid: 9 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x561d95a59fe0 pid: 8 (default app)
Tue Feb 18 20:24:37 2020 - [emperor] vassal leads.ini is ready to accept requests
Error running Core Agent
Traceback (most recent call last):
  File "/leads/env/lib/python3.6/site-packages/scout_apm/core/core_agent_manager.py", line 71, in run
    close_fds=True,
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scout_apm_core/scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu/core-agent': '/tmp/scout_apm_core/scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu/core-agent'
[pid: 9|app: 0|req: 1/1] 172.18.0.1 () {34 vars in 423 bytes} [Tue Feb 18 20:24:57 2020] GET / => generated 2 bytes in 4763 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
```

```
/leads # ls /tmp/scout_apm_core/scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu/
core-agent                                          manifest.json                                       scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu.tgz
/leads # ls /tmp/scout_apm_core/scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu/core-agent 
/tmp/scout_apm_core/scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu/core-agent
/leads # cd /tmp/scout_apm_core/scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu/
/tmp/scout_apm_core/scout_apm_core-v1.2.6-x86_64-unknown-linux-gnu # ./core-agent 
sh: ./core-agent: not found

```

**Comment by cschneid** [comment]
@Vladkryvoruchko alpine linux uses the `musl` libc implementation. To use a musl-specific core agent built, add a new configuration option:

```
SCOUT_CORE_AGENT_TRIPLE=unknown-linux-musl
```

**Comment by Vladkryvoruchko** [comment]
@cschneid Thanks. It worked with a little correction

for Dockerfile it will be:
`ENV SCOUT_CORE_AGENT_TRIPLE x86_64-unknown-linux-musl`
for process:
`SCOUT_CORE_AGENT_TRIPLE=x86_64-unknown-linux-musl`
