### ISSUE TITLE
Django requests randomly fail

### ISSUE THREAD

**Issue by KyeRussell** [scoutapp/scout_apm_python#506]
Hi,

A bit of a weird one.

I have just installed the Scout APM by following the provided instructions. I am having issues with running the APM in development (runserver).

(Most of the time), my initial page load succeeds, along with all static subresources.

However, after some subsequent page loads, I am eventually greeted with "A server error occurred.  Please contact the administrator.", which I understand to only occur when something goes very wrong inside of Django.

Once this occurs, no other page loads succeed until I restart the development server.

Traceback from the console:

```
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
web_1            |     response = get_response(request)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/scout_apm/django/middleware.py", line 161, in __call__
web_1            |     tracked_request = TrackedRequest.instance()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/scout_apm/core/tracked_request.py", line 45, in instance
web_1            |     return context.get_tracked_request()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/scout_apm/core/context.py", line 115, in get_tracked_request
web_1            |     self._local.tracked_request = TrackedRequest()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/asgiref/local.py", line 103, in __setattr__
web_1            |     self._maybe_cleanup()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/asgiref/local.py", line 91, in _maybe_cleanup
web_1            |     self._cleanup()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/asgiref/local.py", line 78, in _cleanup
web_1            |     if not key.is_alive():
web_1            |   File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
web_1            |     self._wait_for_tstate_lock(False)
web_1            |   File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
web_1            |     assert self._is_stopped
web_1            | AssertionError
web_1            | 
web_1            | During handling of the above exception, another exception occurred:
web_1            | 
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
web_1            |     self.result = application(self.environ, self.start_response)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
web_1            |     return self.application(environ, start_response)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__
web_1            |     response = self.get_response(request)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 124, in get_response
web_1            |     response = self._middleware_chain(request)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 43, in inner
web_1            |     response = response_for_exception(request, exc)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception
web_1            |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
web_1            |     return debug.technical_500_response(request, *exc_info)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/views/debug.py", line 84, in technical_500_response
web_1            |     html = reporter.get_traceback_html()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/views/debug.py", line 326, in get_traceback_html
web_1            |     t = DEBUG_ENGINE.from_string(TECHNICAL_500_TEMPLATE)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 155, in from_string
web_1            |     return Template(template_code, engine=self)
web_1            |   File "/usr/local/lib/python3.5/dist-packages/scout_apm/core/stacktracer.py", line 20, in wrapper
web_1            |     tracked_request = TrackedRequest.instance()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/scout_apm/core/tracked_request.py", line 45, in instance
web_1            |     return context.get_tracked_request()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/scout_apm/core/context.py", line 115, in get_tracked_request
web_1            |     self._local.tracked_request = TrackedRequest()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/asgiref/local.py", line 103, in __setattr__
web_1            |     self._maybe_cleanup()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/asgiref/local.py", line 91, in _maybe_cleanup
web_1            |     self._cleanup()
web_1            |   File "/usr/local/lib/python3.5/dist-packages/asgiref/local.py", line 78, in _cleanup
web_1            |     if not key.is_alive():
web_1            |   File "/usr/lib/python3.5/threading.py", line 1113, in is_alive
web_1            |     self._wait_for_tstate_lock(False)
web_1            |   File "/usr/lib/python3.5/threading.py", line 1069, in _wait_for_tstate_lock
web_1            |     assert self._is_stopped
web_1            | AssertionError
```

Given the seemingly random nature of this, and the fact that threading is mentioned, it smells like some sort of race condition.

**Comment by adamchainz** [comment]
Hi @KyeRussell 

This looks like [python issue 29376](https://bugs.python.org/issue29376) which was fixed [in Python 3.5.4](https://docs.python.org/3/whatsnew/changelog.html#python-3-5-4-release-candidate-1).  Are you using 3.5.9, the latest 3.5.x release?

Thanks,

Adam

**Comment by adamchainz** [comment]
Btw, since it looks like you are using Heroku, you should be able to upgrade simply by changing your `runtime.txt`: https://devcenter.heroku.com/articles/python-runtimes , or base docker image.

**Comment by adamchainz** [comment]
Closing due to no reply.
