### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by rsyring** [scoutapp/scout_apm_python#74]
In some of the exceptions that were thrown due to #73, I also saw this exception:

```
  File "flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 33, in reraise
    raise value
  File "flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "scout_apm/flask/__init__.py", line 72, in dispatch_request
    return view_func(**req.view_args)
  File "scout_apm/core/monkey.py", line 212, in __call__
    return self._eop_wrapper_(self.__subject__, *args, **kwargs)
  File "scout_apm/flask/__init__.py", line 115, in tracing_function
    TrackedRequest.instance().tag('error', 'true')
  File "scout_apm/core/tracked_request.py", line 42, in tag
  TypeError: not enough arguments for format string
```

The problem is:

https://github.com/scoutapp/scout_apm_python/blob/1dd5b76f9b4fd65d707111d78a4445254b219e7f/src/scout_apm/core/tracked_request.py#L42

It looks like you want to pass in a tuple to the string formatter, but because you are in a function call, it's being handled as you anticipate.  You probably want:

```python
logger.debug('Overwriting previously set tag for request %s: %s' % (self.req_id, key)) 
```

Although, the Python logger will handle string formatting for you automatically, so I believe this will also work and feels a bit "cleaner" to me.

```python
logger.debug('Overwriting previously set tag for request %s: %s', self.req_id, key) 
```

**Comment by FlyingPigSolutions** [comment]
Having this error since Last July 2018: could it be related?
> Can't validate some entries:

```
Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-server/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-server/addons/account_asset/models/account.py", line 24, in post
    return super(AccountMove, self).post()
  File "/home/odoo/odoo-server/addons/account/models/account_move.py", line 160, in post
    new_name = sequence.with_context(ir_sequence_date=move.date).next_by_id()
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 263, in next_by_id
    return self._next()
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 257, in _next
    return seq_date.with_context(ir_sequence_date_range=seq_date.date_from)._next()
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 352, in _next
    return self.sequence_id.get_next_char(number_next)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 224, in get_next_char
    interpolated_prefix, interpolated_suffix = self._get_prefix_suffix()
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 217, in _get_prefix_suffix
    interpolated_prefix = _interpolate(self.prefix, d)
  File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_sequence.py", line 194, in _interpolate
    return (s % d) if s else ''
TypeError: not enough arguments for format string
```

**Comment by cschneid** [comment]
Hi @FlyingPigSolutions, I don't think that's the Scout agent, although I'd be interested to know if it occurs only when we're installed.

It looks like the error is in the ir_sequence file, which isn't part of our agent. Specifically the code probably has multiple placeholders in `s`, but only 1 value (`d`) is being provided:
```
return (s % d) if s else ''
```

**Comment by FlyingPigSolutions** [comment]
Indeed Chris @cschneid, sorry to mix up issues. I realise I post it a little fast after looking similar issues on google.
Although I understand the issue, I don't understand where it comes from as its not from a module installation.
Appreciate if you would have a clue, but I'll dig some more too.

**Comment by adamchainz** [comment]
Just to chime in - it seems to be this file in odoo: https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_sequence.py#L193 . I haven't quite understood all the code there but it might be coming from parsing some configuration file? You might be able to raise an issue there.

**Comment by FlyingPigSolutions** [comment]
Thank you Adam @adamchainz that helps.
I was looking into the odoo config sequences to see what would cause this issue when :
- its not creating an error for all sequences
- it creates it only on one

However, making changes on the sequences, didn't solved it.
I don't think I have to get into the code itself and make any change.

I believe it is more during configuration that it creates the issue afterwards.

**Comment by FlyingPigSolutions** [comment]
I don't think I should touch the code there https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_sequence.py#L193 
Is it possible to come from a python version? Should I pass to python 3.6 ?

**Comment by cschneid** [comment]
Hi @FlyingPigSolutions - I'm not sure we're the best ones to help you with Odoo, this repo is for our ScoutAPM product which doesn't seem to be interacting with anything here. Can I have you create an issue over at https://github.com/it-projects-llc/odoo-development/issues?

**Comment by FlyingPigSolutions** [comment]
Updating the python3 didn't solve the issue

**Comment by FlyingPigSolutions** [comment]
@cschneid sure thanks
